name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.0.0
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archives"
        echo "Package 0: ${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "Package 1: ${{ steps.makepkg.outputs.pkgfile1 }}"
    # Uncomment to upload an artifact
    # - name: Upload Package Archive
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: ${{ steps.makepkg.outputs.pkgfile0 }}
    #     path: ${{ steps.makepkg.outputs.pkgfile0 }}
